package viabluetooth.tugasAkhir.menu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import viabluetooth.tugasAkhir.booking.booking;
import viabluetooth.tugasAkhir.koneksi.koneksi;
import viabluetooth.tugasAkhir.login.Login;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MenuLogin extends javax.swing.JFrame {

    int code;
    DateFormat dateFormat;
    Date date;
    boolean enable = true;
    DefaultTableModel tabel = new DefaultTableModel();
    private String jasa;
    /**
     * Creates new form MenuLogin
     */
    public MenuLogin() {
        initComponents();
        tampil_combo();
        txt_trans.setEnabled(false);
        txt_hari.setEnabled(false);
        mbl_combobox.setEnabled(false);
        txt_plat.setEnabled(false);
        txt_harga.setEnabled(false);
        txt_tgl.setEnabled(false);
        jRadio_ya.setEnabled(false);
        jRadio_tidak.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mbl_combobox = new javax.swing.JComboBox<>();
        txt_hari = new javax.swing.JTextField();
        jRadio_ya = new javax.swing.JRadioButton();
        jRadio_tidak = new javax.swing.JRadioButton();
        btn_booking = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_trans = new javax.swing.JTextField();
        btn_new = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_plat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MAGNUM RENT CAR MALANG");

        jLabel2.setText("Pilih Mobil untuk sewa");

        jLabel3.setText("Lama Peminjaman (Hari)");

        jLabel4.setText("Sewa Sopir");

        mbl_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih mobil-" }));
        mbl_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbl_comboboxActionPerformed(evt);
            }
        });

        btn_group.add(jRadio_ya);
        jRadio_ya.setText("Pakai");
        jRadio_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_yaActionPerformed(evt);
            }
        });

        btn_group.add(jRadio_tidak);
        jRadio_tidak.setText("Tidak Pakai");
        jRadio_tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_tidakActionPerformed(evt);
            }
        });

        btn_booking.setText("booking");
        btn_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingActionPerformed(evt);
            }
        });

        jLabel5.setText("No. Transaksi");

        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_batal.setText("batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Pinjam ");

        txt_tgl.setDateFormatString("yyyy-MM-dd");
        txt_tgl.setMaxSelectableDate(new java.util.Date(1546189200000L));
        txt_tgl.setMinSelectableDate(new java.util.Date(1514739600000L));

        jLabel7.setText("No. Plat");

        txt_plat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_platActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga Sewa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadio_ya)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_tidak))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_hari)
                    .addComponent(txt_harga)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_batal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_booking))
                    .addComponent(mbl_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_plat))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_new))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mbl_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_ya)
                    .addComponent(jLabel4)
                    .addComponent(jRadio_tidak))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal)
                    .addComponent(btn_booking))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingActionPerformed
        // TODO add your handling code here:
        String no_trans = txt_trans.getText();
        String value = mbl_combobox.getSelectedItem().toString();
        String plat = txt_plat.getText();
        String tgl = ((JTextField) txt_tgl.getDateEditor().getUiComponent()).getText();
        
        if(value.equals("")){
            JOptionPane.showMessageDialog(null, "Pilihlah Mobil");
        } else if(tgl.equals("")){
            JOptionPane.showMessageDialog(null, "Tentukan tanggal");
        } else if(jasa.equals("")){
            JOptionPane.showMessageDialog(null, "isi salah satu");
/*        } else if(checkValid(tgl)){
            JOptionPane.showMessageDialog(null, "Sudah Terbooking");
            new MenuLogin().setVisible(true);
            this.dispose();
        } else if(checkMobil(value)){
            JOptionPane.showMessageDialog(null, "Sudah Terbooking");
            new MenuLogin().setVisible(true);
            this.dispose();
        } else if(checkValid(tgl) && (checkMobil(value))){
            JOptionPane.showMessageDialog(null, "Sudah Terbooking");
            new MenuLogin().setVisible(true);
            this.dispose(); */
        } else {
            PreparedStatement ps;
            String query = "INSERT INTO `booking`(`no_trans`, `nama_mobil`, `no_plat`, `tgl_pinjam`, `sopir`) VALUES (?,?,?,?,?)";

            try {
                ps = koneksi.getConnection().prepareStatement(query);
                ps.setString(1, no_trans);
                ps.setString(2, value);
                ps.setString(3, plat);
                ps.setString(4, tgl);
                ps.setString(5, jasa);

                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "Berhasil Booking !");
                    booking bkg = new booking();
                    bkg.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Booking Gagal !");
                    new MenuLogin().setVisible(true);
                    this.dispose();
                }

            } catch (SQLException ex) {
                Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_bookingActionPerformed
    
    public boolean checkMobil(String nama){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkMobil = false;
        String query = "SELECT * FROM `booking` WHERE `nama` =?";
        
        try {
            ps = koneksi.getConnection().prepareStatement(query);
            ps.setString(1, nama);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkMobil = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkMobil;
    }
    
    public boolean checkValid(String tgl_pinjam){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkValid = false;
        String query = "SELECT * FROM `booking` WHERE `tgl_pinjam` =?";
        
        try {
            ps = koneksi.getConnection().prepareStatement(query);
            ps.setString(1, tgl_pinjam);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkValid = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkValid;
    }

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyMMdd");
        Date date = new Date();
        System.out.println(dateFormat.format(date));
        code++;
        txt_trans.setText(dateFormat.format(date)+String.format("%02d", code));
        txt_trans.setEnabled(false);
        btn_new.setEnabled(false);
        mbl_combobox.setEnabled(true);
        txt_plat.setEnabled(false);
        txt_harga.setEnabled(false);
        txt_hari.setEnabled(true);
        jRadio_ya.setEnabled(true);
        jRadio_tidak.setEnabled(true);
        txt_tgl.setEnabled(true);
        btn_booking.setEnabled(true);
        btn_batal.setEnabled(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        new MenuLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_platActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_platActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_platActionPerformed

    private void mbl_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbl_comboboxActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_mbl_comboboxActionPerformed

    private void jRadio_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_yaActionPerformed
        // TODO add your handling code here:
        jasa="pakai";
    }//GEN-LAST:event_jRadio_yaActionPerformed

    private void jRadio_tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_tidakActionPerformed
        // TODO add your handling code here:
        jasa="tidak pakai";
    }//GEN-LAST:event_jRadio_tidakActionPerformed

    public void tampil_combo(){
            try {
                Connection con = koneksi.getConnection();
                Statement stat = con.createStatement();
                String query = "SELECT nama FROM mobil ORDER BY nama ASC";
                ResultSet rs = stat.executeQuery(query);

                while(rs.next()){
                    Object[] ob = new Object[3];
                    ob[0] = rs.getString(1);
                    mbl_combobox.addItem((String) ob[0]);                           
                }
              } catch (Exception e) {
                    System.out.println(e.getMessage());
            }
    }
    
    public void tampil()
    {
        try {
        Connection con = koneksi.getConnection();
        Statement stat = con.createStatement();
        String query = "SELECT plat, harga FROM mobil WHERE nama='"+mbl_combobox.getSelectedItem()+"'";  
        ResultSet rs = stat.executeQuery(query);
        
            while(rs.next()){
                Object[] ob = new Object[3];
                ob[0]=  rs.getString(1);
                ob[1]= rs.getString(2);

                txt_plat.setText((String) ob[0]);
                txt_harga.setText((String) ob[1]);
            }
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_booking;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_new;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadio_tidak;
    private javax.swing.JRadioButton jRadio_ya;
    private javax.swing.JComboBox<String> mbl_combobox;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_hari;
    private javax.swing.JTextField txt_plat;
    private com.toedter.calendar.JDateChooser txt_tgl;
    private javax.swing.JTextField txt_trans;
    // End of variables declaration//GEN-END:variables
}
